spring:
  application:
    name: alchemy-application
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/alchemy}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    platform: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 0
  servlet:
    context-path: /alchemy-application/

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

kafka:
  server: ${KAFKA_SERVER:http://localhost:9092}
  groupId1: fixed-answer-task.2

authentication:
  jwt:
    secretKey: chemcool