spring:
  application:
    name: answers-application
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/answers_task}
    username: ${SPRING_DATASOURCE_USERNAME:mick}
    password: ${SPRING_DATASOURCE_PASSWORD:mick}
    platform: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 0
  servlet:
    context-path: /answers-application/

kafka:
  server: ${KAFKA_SERVER:http://localhost:9092}
  groupId1: fixed-answer-task.2
  groupId2: matching-task.2
  groupId3: tasks-single-select-service.2
  groupId4: equations-task.2

authentication:
  jwt:
    secretKey: chemcool