spring:
  jpa:
    database: postgresql
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/chemsingleselect
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 0
  servlet:
    context-path: /chemsingleselect-application/

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

kafka:
  server: http://localhost:9092
  groupId: tasks-single-select-service.1

---
spring:
  profiles: test-localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks_single_select
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver
  cloud:
    config:
      test:
        message: Это тестовое сообщение для проверки работы Spring Cloud Config Server храниться в CONFIG-REPO-ENV в модуле configuration
