spring:
  appclication:
    name: tasks-application
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      properties:
        spring:
          json:
            type:
              mapping: "singleSelectTask:com.chemcool.school.tasks.domain.SingleSelectTask,
                  comparison:com.chemcool.school.tasks.domain.Comparison,
                  fixedAnswerTask:com.chemcool.school.tasks.domain.FixedAnswerTask"

server:
  port: 0
  servlet:
    context-path: /tasks-application/

kafka:
  server: http://localhost:9092
  groupId: constructor-task.1

authentication:
  jwt:
    secretKey: 926D96C90030DD58429D2751AC1BDBBC


