spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/theory_application
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver
    kafka:
      producer:
        properties:
          spring:
            json:
              type:
                mapping: "theoryTask: com.chemcool.school.constructor.domain.TheoryTask"


server:
  port: 0
  servlet:
    context-path: /theory-application/

kafka:
  server: http://localhost:9092
  groupId: theory-application

