spring:
  application:
    name: tasks-application
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 9090
  servlet:
    context-path: /tasks-application/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  server: http://localhost:9092
  taskCemEquationsGroupId: task-chemistry-equations.1
  taskChemFixedAnswerGroupId: task-chemistry-answer.1
  taskChemMatchesGroupId: task-chemistry-matches.1
  taskChemSingleSelectGroupId: task-chemistry-singleSelect.1

